// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZW_NVh8Z_JeouX3haVOXDqb1V95Hjssk',
    appId: '1:954133221148:web:1a6c8638f5209e4c64b4d9',
    messagingSenderId: '954133221148',
    projectId: 'moc-firebase-2a2e7',
    authDomain: 'moc-firebase-2a2e7.firebaseapp.com',
    storageBucket: 'moc-firebase-2a2e7.appspot.com',
    measurementId: 'G-14D5DQ7JY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuD9PjYZioR_T0W7bw4xno4o5xzjorFv8',
    appId: '1:954133221148:android:a0427d3f0958345d64b4d9',
    messagingSenderId: '954133221148',
    projectId: 'moc-firebase-2a2e7',
    storageBucket: 'moc-firebase-2a2e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl36-uXvuG5UWSGFokLcXzzyrrMXWSaoA',
    appId: '1:954133221148:ios:cee0dbeb4114921864b4d9',
    messagingSenderId: '954133221148',
    projectId: 'moc-firebase-2a2e7',
    storageBucket: 'moc-firebase-2a2e7.appspot.com',
    iosClientId: '954133221148-qvc57ebnuhvml880ccoqcrndp3mmt69i.apps.googleusercontent.com',
    iosBundleId: 'com.example.mocFirebase',
  );
}
